class ModeloTecnologicos {
  List<String> institutos = [
    'Centros de investigación',
    'Institutos tecnológicos federales',
    'Institutos Tecnológicos Descentralizados'
  ];

  List<String> centros = [
    'Centro Nacional de Investigación y Desarrollo Tecnológico',
    'Centro Interdisciplinario de Investigación y Docencia en Educación Técnica',
    'Centro Regional de Optimización y Desarrollo de Equipo Celaya',
    'Centro Regional de Optimización y Desarrollo de Equipo Chihuahua',
    'Centro Regional de Optimización y Desarrollo de Equipo Mérida',
    'Centro Regional de Optimización y Desarrollo de Equipo Orizaba',
  ];
  List<String> tecnologicosF = [
    'Instituto Tecnológico de Acapulco',
    'Instituto Tecnológico de Agua Prieta',
    'Instituto Tecnológico de Aguascalientes',
    'Instituto Tecnológico de Altamira',
    'Instituto Tecnológico de Altiplano de Tlaxcala',
    'Instituto Tecnológico de Álvaro Obregón',
    'Instituto Tecnológico de Apizaco',
    'Instituto Tecnológico de Atitalaquia',
    'Instituto Tecnológico de Bahía de Banderas',
    'Instituto Tecnológico de Boca del Rio',
    'Instituto Tecnológico de Campeche',
    'Instituto Tecnológico de Cancún',
    'Instituto Tecnológico de Celaya',
    'Instituto Tecnológico de Cerro Azul',
    'Instituto Tecnológico de Chetumal',
    'Instituto Tecnológico de Chihuahua',
    'Instituto Tecnológico de Chihuahua II',
    'Instituto Tecnológico de Chilpancingo',
    'Instituto Tecnológico de China',
    'Instituto Tecnológico de Ciudad Altamirano',
    'Instituto Tecnológico de Ciudad Cuauhtémoc',
    'Instituto Tecnológico de Ciudad Guzmán',
    'Instituto Tecnológico de Ciudad Jiménez',
    'Instituto Tecnológico de Ciudad Juárez',
    'Instituto Tecnológico de Ciudad Madero',
    'Instituto Tecnológico de Ciudad Valles',
    'Instituto Tecnológico de Ciudad Victoria',
    'Instituto Tecnológico de Colima',
    'Instituto Tecnológico de Comitán',
    'Instituto Tecnológico de Comitancillo',
    'Instituto Tecnológico de Conkal',
    'Instituto Tecnológico de Costa Grande',
    'Instituto Tecnológico de Cuautla',
    'Instituto Tecnológico de Culiacán',
    'Instituto Tecnológico de Delicias',
    'Instituto Tecnológico de Durango',
    'Instituto Tecnológico de El Llano Aguascalientes',
    'Instituto Tecnológico de El Salto',
    'Instituto Tecnológico de Ensenada',
    'Instituto Tecnológico de Frontera Comalapa',
    'Instituto Tecnológico de Guaymas',
    'Instituto Tecnológico de Gustavo A. Madero',
    'Instituto Tecnológico de Gustavo A. Madero II',
    'Instituto Tecnológico de Hermosillo',
    'Instituto Tecnológico de Huatabampo',
    'Instituto Tecnológico de Huejutla',
    'Instituto Tecnológico de Huimanguillo',
    'Instituto Tecnológico de Iguala',
    'Instituto Tecnológico de Istmo',
    'Instituto Tecnológico de Iztapalapa',
    'Instituto Tecnológico de Iztapalapa II',
    'Instituto Tecnológico de Iztapalapa III',
    'Instituto Tecnológico de Jiquilpan',
    'Instituto Tecnológico de La Chontalpa',
    'Instituto Tecnológico de La Cuenca del Papaloapan',
    'Instituto Tecnológico de La Laguna',
    'Instituto Tecnológico de La Paz',
    'Instituto Tecnológico de La Piedad',
    'Instituto Tecnológico de La Región Mixe',
    'Instituto Tecnológico de La Zona Maya',
    'Instituto Tecnológico de La Zona Olmeca',
    'Instituto Tecnológico de Lázaro Cárdenas',
    'Instituto Tecnológico de León',
    'Instituto Tecnológico de Lerma',
    'Instituto Tecnológico de Linares',
    'Instituto Tecnológico de Los Mochis',
    'Instituto Tecnológico de Matamoros',
    'Instituto Tecnológico de Matehuala',
    'Instituto Tecnológico de Mazatlán',
    'Instituto Tecnológico de Mérida',
    'Instituto Tecnológico de Mexicali',
    'Instituto Tecnológico de Milpa Alta',
    'Instituto Tecnológico de Milpa Alta II',
    'Instituto Tecnológico de Minatitlán',
    'Instituto Tecnológico de Morelia',
    'Instituto Tecnológico de Nogales',
    'Instituto Tecnológico de Norte de Nayarit',
    'Instituto Tecnológico de Nuevo Laredo',
    'Instituto Tecnológico de Nuevo León',
    'Instituto Tecnológico de Oaxaca',
    'Instituto Tecnológico de Ocotlán',
    'Instituto Tecnológico de Orizaba',
    'Instituto Tecnológico de Pabellón de Arteaga',
    'Instituto Tecnológico de Pachuca',
    'Instituto Tecnológico de Parral',
    'Instituto Tecnológico de Piedras Negras',
    'Instituto Tecnológico de Pinotepa',
    'Instituto Tecnológico de Pochutla',
    'Instituto Tecnológico de Puebla',
    'Instituto Tecnológico de Querétaro',
    'Instituto Tecnológico de Reynosa',
    'Instituto Tecnológico de Roque',
    'Instituto Tecnológico de Salina Cruz',
    'Instituto Tecnológico de Saltillo',
    'Instituto Tecnológico de San Juan del Rio',
    'Instituto Tecnológico de San Luis Potosí',
    'Instituto Tecnológico de San Marcos',
    'Instituto Tecnológico de Sinaloa de Leyva',
    'Instituto Tecnológico de Sur De Nayarit',
    'Instituto Tecnológico de Tapachula',
    'Instituto Tecnológico de Tecomatlán',
    'Instituto Tecnológico de Tehuacán',
    'Instituto Tecnológico de Tepic',
    'Instituto Tecnológico de Tijuana',
    'Instituto Tecnológico de Tizimín',
    'Instituto Tecnológico de Tláhuac',
    'Instituto Tecnológico de Tláhuac II',
    'Instituto Tecnológico de Tláhuac III',
    'Instituto Tecnológico de Tlajomulco',
    'Instituto Tecnológico de Tlalnepantla',
    'Instituto Tecnológico de Tlalpan',
    'Instituto Tecnológico de Tlaxiaco',
    'Instituto Tecnológico de Toluca',
    'Instituto Tecnológico de Torreón',
    'Instituto Tecnológico de Tuxtepec',
    'Instituto Tecnológico de Tuxtla Gutiérrez',
    'Instituto Tecnológico de Úrsulo Galván',
    'Instituto Tecnológico de Valle de Morelia',
    'Instituto Tecnológico de Valle de Oaxaca',
    'Instituto Tecnológico de Valle del Guadiana',
    'Instituto Tecnológico de Valle del Yaqui',
    'Instituto Tecnológico de Veracruz',
    'Instituto Tecnológico de Villahermosa',
    'Instituto Tecnológico de Zacatecas',
    'Instituto Tecnológico de Zacatepec',
    'Instituto Tecnológico de Zitácuaro',
  ];

  List<String> tecnologicosD = [
    'Instituto Tecnológico Superior de Acatlán de Osorio',
    'Instituto Tecnológico Superior de Acayucan',
    'Instituto Tecnológico Superior de Álamo Temapache',
    'Instituto Tecnológico Superior de Alvarado',
    'Instituto Tecnológico Superior de Apatzingán',
    'Instituto Tecnológico Superior de Arandas',
    'Instituto Tecnológico Superior de Atlixco',
    'Instituto Tecnológico Superior de Cajeme',
    'Instituto Tecnológico Superior de Calkiní',
    'Instituto Tecnológico Superior de Cananea',
    'Instituto Tecnológico Superior de Centla',
    'Instituto Tecnológico Superior de Champotón',
    'Instituto Tecnológico Superior de Chapala',
    'Instituto Tecnológico Superior de Chicontepec',
    'Instituto Tecnológico Superior de Cintalapa',
    'Instituto Tecnológico Superior de Ciudad Acuña',
    'Instituto Tecnológico Superior de Ciudad Constitución',
    'Instituto Tecnológico Superior de Ciudad Hidalgo',
    'Instituto Tecnológico Superior de Ciudad Serdán',
    'Tecnológico de Estudios Superiores de Coacalco',
    'Instituto Tecnológico Superior de Coalcomán',
    'Instituto Tecnológico Superior de Coatzacoalcos',
    'Instituto Tecnológico Superior de Cocula',
    'Instituto Tecnológico Superior de Comalcalco',
    'Instituto Tecnológico Superior de Cosamaloapan',
    'Instituto Tecnológico Superior de Ébano',
    'Instituto Tecnológico Superior de El Grullo',
    'Instituto Tecnológico Superior de El Dorado',
    'Instituto Tecnológico Superior de Escárcega',
    'Instituto Tecnológico Superior de Felipe Carrillo Puerto',
    'Instituto Tecnológico Superior de Fresnillo',
    'Instituto Tecnológico Superior de Guanajuato',
    'Instituto Tecnológico Superior de Guasave',
    'Instituto Tecnológico Superior de Huatusco',
    'Instituto Tecnológico Superior de Huauchinango',
    'Instituto Tecnológico Superior de Huetamo',
    'Instituto Tecnológico Superior de Huichapan',
    'Instituto Tecnológico Superior de Irapuato',
    'Instituto Tecnológico Superior de Jerez',
    'Instituto Tecnológico Superior de Jesús Carranza',
    'Instituto Tecnológico Superior de Juan Rodríguez Clara',
    'Instituto Tecnológico Superior de La Costa Chica',
    'Instituto Tecnológico Superior de La Huerta',
    'Instituto Tecnológico Superior de La Montaña',
    'Instituto Tecnológico de Estudios Superiores de La Región Carbonífera',
    'Instituto Tecnológico Superior de La Región de Los Llanos',
    'Instituto Tecnológico Superior de La Región Sierra',
    'Instituto Tecnológico Superior de La Sierra Negra de Ajalpan',
    'Instituto Tecnológico Superior de La Sierra Norte de Puebla',
    'Instituto Tecnológico Superior de Lagos de Moreno',
    'Instituto Tecnológico Superior de Las Choapas',
    'Instituto Tecnológico Superior de Lerdo',
    'Instituto Tecnológico Superior de Libres',
    'Instituto Tecnológico Superior de Loreto',
    'Instituto Tecnológico de Estudios Superiores de Los Cabos',
    'Instituto Tecnológico Superior de Los Reyes',
    'Instituto Tecnológico Superior de Los Ríos',
    'Instituto Tecnológico Superior de Macuspana',
    'Instituto Tecnológico Superior de Mante',
    'Instituto Tecnológico Superior de Martínez de La Torre',
    'Instituto Tecnológico Superior de Mascota',
    'Instituto Tecnológico Superior de Misantla',
    'Instituto Tecnológico Superior de Monclova',
    'Instituto Tecnológico Superior de Motul',
    'Instituto Tecnológico Superior de Mulegé',
    'Instituto Tecnológico Superior de Múzquiz',
    'Instituto Tecnológico Superior de Naranjos',
    'Instituto Tecnológico Superior de Nochistlán',
    'Instituto Tecnológico Superior de Nuevo Casas Grandes',
    'Instituto Tecnológico Superior de Occidente del Estado de Hidalgo',
    'Instituto Tecnológico Superior de Oriente del Estado de Hidalgo',
    'Instituto Tecnológico Superior de P´Urhépecha',
    'Instituto Tecnológico Superior de Pánuco',
    'Instituto Tecnológico Superior de Pátzcuaro',
    'Instituto Tecnológico Superior de Perote',
    'Instituto Tecnológico Superior de Poza Rica',
    'Instituto Tecnológico Superior de Progreso',
    'Instituto Tecnológico Superior de Puerto Peñasco',
    'Instituto Tecnológico Superior de Puerto Vallarta',
    'Instituto Tecnológico Superior de Puruándiro',
    'Instituto Tecnológico Superior de Rioverde',
    'Instituto Tecnológico Superior de Salvatierra',
    'Instituto Tecnológico Superior de San Andrés Tuxtla',
    'Instituto Tecnológico Superior de San Luis Potosí, Capital',
    'Instituto Tecnológico Superior de San Martín Texmelucan',
    'Instituto Tecnológico Superior de San Miguel el Grande',
    'Instituto Tecnológico Superior de San Pedro de las Colonias',
    'Instituto Tecnológico Superior de Santa María de El Oro',
    'Instituto Tecnológico Superior de Santiago Papasquiaro',
    'Instituto Tecnológico Superior de Sur de Guanajuato',
    'Instituto Tecnológico Superior de Sur del Estado de Yucatán',
    'Instituto Tecnológico Superior de Tacámbaro',
    'Instituto Tecnológico Superior de Tala',
    'Instituto Tecnológico Superior de Tamazula de Gordiano',
    'Instituto Tecnológico Superior de Tamazunchale',
    'Instituto Tecnológico Superior de Tantoyuca',
    'Instituto Tecnológico Superior de Tepeaca',
    'Instituto Tecnológico Superior de Tepexi de Rodríguez',
    'Instituto Tecnológico Superior de Teposcolula',
    'Instituto Tecnológico Superior de Tequila',
    'Instituto Tecnológico Superior de Teziutlán',
    'Tecnológico de Estudios Superiores de Tianguistenco',
    'Instituto Tecnológico Superior de Tierra Blanca',
    'Instituto Tecnológico Superior de Tlatlauquitepec',
    'Instituto Tecnológico Superior de Tlaxco',
    'Instituto Tecnológico Superior de Uruapan',
    'Instituto Tecnológico Superior de Valladolid',
    'Instituto Tecnológico Superior de Venustiano Carranza',
    'Instituto Tecnológico Superior de Villa La Venta',
    'Instituto Tecnológico Superior de Xalapa',
    'Instituto Tecnológico Superior de Zacapoaxtla',
    'Instituto Tecnológico Superior de Zacatecas Norte',
    'Instituto Tecnológico Superior de Zacatecas Occidente',
    'Instituto Tecnológico Superior de Zacatecas Sur',
    'Instituto Tecnológico de Estudios Superiores de Zamora',
    'Instituto Tecnológico Superior de Zapopan',
    'Instituto Tecnológico Superior de Zapotlanejo',
    'Instituto Tecnológico Superior de Zongolica',
    'Tecnológico de Estudios Superiores de Chalco',
    'Tecnológico de Estudios Superiores de Chimalhuacán',
    'Tecnológico de Estudios Superiores de Cuautitlán Izcalli',
    'Tecnológico de Estudios Superiores de Ecatepec',
    'Tecnológico de Estudios Superiores de Huixquilucan',
    'Tecnológico de Estudios Superiores de Ixtapaluca',
    'Tecnológico de Estudios Superiores de Jilotepec',
    'Tecnológico de Estudios Superiores de Jocotitlán',
    'Tecnológico de Estudios Superiores de Oriente del Estado de México',
    'Tecnológico de Estudios Superiores de San Felipe del Progreso',
    'Tecnológico de Estudios Superiores de Valle de Bravo',
    'Tecnológico de Estudios Superiores de Villa Guerrero',
  ];

  List<String> carrera = [
    'Ambiental',
    'Ing. Ambiental',
    'Ing. Bioquímica',
    'Ing. Civil',
    'Ing. Eléctrica',
    'Ing. Electromecánica',
    'Ing. Electrónica',
    'Ing. en Agronomía',
    'Ing. en Geociencias',
    'Ing. en Materiales',
    'Ing. en Sistemas Computacionales',
    'Ing. Industrial',
    'Ing. Mecánica',
    'Ing. Química',
    'Lic. en Informática',
    'Lic. en Biología',
    'Lic. en Administración',
    'Lic. en Contaduría',
    'Ing. en Mecatrónica',
    'Ing. en Industrias Alimentarias',
    'Ing. en Desarrollo Comunitario',
    'Ing. en Pesquerías',
    'Ing. en Acuicultura',
    'Ing. en Innovación Agrícola Sustentable',
    'Ing. Forestal',
    'Ing. Naval',
    'Ing. en Logística',
    'Ing. en Nanotecnología',
    'Lic. en Gastronomía',
    'Ing. en Gestión Empresarial',
    'Contador Público',
    'Ing. en Energías renovables',
    'Ing. en Administración',
    'Ing. Informática',
    'Ing. en Tecnologías de la Información y Comunicaciones',
    'Ing. Petrolera',
    'Ing. en Animación Digital y Efectos Visuales',
    'Ing. en Minería',
    'Ing. Hidrológica',
    'Ing. Aeronaútica',
    'Ing. en Sistemas Automotrices',
    'Ing. Biomédica',
    'Lic. en Turismo',
    'Ing. en Biotecnología',
    'Técnico Superior en Minería',
    'Ing. en Diseño Industrial',
    'Técnico Superior en Buceo Industrial',
    'Otra...'
  ];

  List<String> categorias = [
    'Sector Agroalimentario',
    'Industria Eléctrica y Electrónica',
    'Electromovilidad y Ciudades Inteligentes',
    'Servicios para la Salud',
    'Industrias Creativas',
    'Cambio Climático',
  ];

  List<String> sectorAlimentario = [
    'Industria alimentaria',
    'Tecnificación de la producción agrícola',
    'Producción pecuaria',
    'Insumos (semillas, fertilizantes, abonos, maquinaria y equipo)',
    'Nuevos modelos de agricultura',
    'Agricultura urbana',
    'Alimentos del futuro',
    'Ingeniería genética verde',
    'Granjas verticales',
    'Autonomía alimentaria',
    'Otro...'
  ];

  List<String> indElectrica = [
    'Electrodomésticos',
    'Equipos de comunicación y medición',
    'Equipo de cómputo',
    'Manufacturas para exportación',
    'Semiconductores',
    'Internet de las cosas (IoT)',
    'Dispositivos eléctricos, electrónicos, mecatrónicos',
    'Tecnología 5G',
    'Robótica y automatización',
    'Otro...',
  ];

  List<String> electromovilidad = [
    'Autopartes',
    'Batería y sus componentes',
    'Vehículos ligeros y de carga',
    'Vehículos de transporte público',
    'Movilidad social',
    'Desarrollo urbano',
    'Otro...',
  ];

  List<String> serviciosSalud = [
    'Equipamiento y dispositivos médicos (rehabilitación, prótesis, etc.)',
    'Biotecnología, nanotecnología, biomedicina',
    'Sistemas de atención médica inteligentes',
    'Medicamentos y productos relacionados',
    'Salud mental',
    'Otro...',
  ];

  List<String> industriasCreativas = [
    'Industria fílmica',
    'Industria televisiva',
    'Videojuegos',
    'Entretenimiento en vivo',
    'Plataformas virtuales',
    'Producción cultural',
    'Aplicaciones tecnológicas para moda y derivados (vestido, calzado, etc.)',
    'Otro...',
  ];

  List<String> cambioClimatico = [
    'Energía verde (eólica, solar, hidrógeno, etc.)',
    'Desalinización',
    'Tecnología aplicada al reciclaje, transformación o tratamiento de agua, sólidos, plásticos y residuos peligrosos',
    'Proyectos que propongan estrategias para mitigar el cambio climático',
    'Ecotecnologías',
    'Transición energética',
    'Sistemas de ahorro y aprovechamiento de agua pluvial',
    'Educación ambiental',
    'Otro...',
  ];

  List<String> naturalezaTecnica = [
    'Agronómicas',
    'Ciencias del Mar',
    'Ciencias de la Tierra',
    'Ciencias Computacionales',
    'Ciencias Ambientales',
    'Ciencias Químicas',
    'Ciencias Mecánicas',
    'Ciencias Eléctricas',
    'Ciencias de los Materiales',
    'Ciencias de Ingeniería Inductriales',
    'Ciencias Económico-Administrativas'
  ];
}
